my_list = [1,2,3]

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [7]:
li = [[1,2,3],[3,4,6]]
np.array(li)

array([[1, 2, 3],
       [3, 4, 6]])

In [8]:
np.random.rand(5)

array([0.80194431, 0.36818474, 0.32403567, 0.56383435, 0.89597745])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.random.rand(5,5)

array([[0.82111529, 0.30663541, 0.13477476, 0.27701805, 0.6529761 ],
       [0.66492064, 0.33012635, 0.85877993, 0.12870241, 0.1280474 ],
       [0.31040506, 0.32178602, 0.96783422, 0.27895157, 0.93965929],
       [0.93414822, 0.41373932, 0.99802035, 0.86299461, 0.40926797],
       [0.51089948, 0.04749581, 0.22077303, 0.93040967, 0.002389  ]])

In [13]:
np.random.randint(1,100,(2,2))

array([[30, 82],
       [99,  5]])

In [14]:
arr = np.random.randint(0,100,25)

In [15]:
arr.reshape(5,5)

array([[45, 64, 67, 84, 76],
       [37, 34, 48, 39, 46],
       [50, 45, 87,  9, 85],
       [94, 89, 21, 63, 43],
       [12, 42, 64, 53,  3]])

In [16]:
ar = np.arange(0,5)

In [17]:
ar * ar

array([ 0,  1,  4,  9, 16])

In [18]:
ar - 10

array([-10,  -9,  -8,  -7,  -6])

In [19]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [20]:
np.log(ar)

/tmp/ipykernel_7954/3877308065.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [21]:
ar/ar

/tmp/ipykernel_7954/2192729293.py:1: RuntimeWarning: invalid value encountered in true_divide
  ar/ar


array([nan,  1.,  1.,  1.,  1.])

In [22]:
ar.max()

4

In [23]:
np.max(ar)

4

In [24]:
np.full((10),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [27]:
np.eye(3) * 5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [46]:
mt = np.arange(1,26).reshape(5,5)

In [48]:
mt[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])